name: Kafka with 1 topic

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: openjdk:21-bookworm

    services:
      kafka:
        image: bitnami/kafka:4.0.0
        ports:
          - 9092:9092
        env:
          KAFKA_ENABLE_KRAFT: yes
          KAFKA_CFG_NODE_ID: 1
          KAFKA_CFG_PROCESS_ROLES: broker,controller
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_CREATE_TOPICS: "quickstart:1:1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Install dependencies
      #  run: |
      #    apt-get update
      #    apt-get install -y xxx

      - name: Wait for Kafka server
        run: |
          echo "Waiting for Kafka to be ready..."
          for i in {1..30}; do
            # nc -z localhost 9092 && echo "Kafka is up!" && break
            # Try listing topics; if it works, Kafka is ready
            if /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1; then
              echo "Kafka is up!"
              break
            fi
            echo "Kafka not ready yet..."
            sleep 2
          done

      - name: Build
        run: |
          ./gradlew build -x test

      - name: Run
        run: |
          ./gradlew run
        env:
          BOOTSTRAP_SERVERS: kafka:9092

      - name: Test
        run: |
          ./gradlew test --tests="KafkaClient1TopicTest"
        env:
          BOOTSTRAP_SERVERS: kafka:9092

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/html

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: ./reports

      - name: Publish reports
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
          commit_message: "Publish test reports"
          keep_files: false
