name: Kafka Example

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: openjdk:21-jdk

    services:
      kafka:
        image: bitnami/kafka:4.0.0
        ports:
          - 9092:9092
        env:
          KAFKA_ENABLE_KRAFT: yes
          KAFKA_CFG_NODE_ID: 1
          KAFKA_CFG_PROCESS_ROLES: broker,controller
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_CREATE_TOPICS: "quickstart:1:1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y netcat xargs

      - name: Wait for Kafka server
        run: |
          sudo apt-get update && sudo apt-get install -y netcat
          echo "Waiting for Kafka..."
          for i in {1..30}; do
            nc -z localhost 9092 && echo "Kafka is up!" && break
            echo "Kafka not ready yet..."
            sleep 2
          done

      - name: Build
        run: |
          ./gradlew build

      - name: Run
        run: |
          ./gradlew run
